# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.CharField(default='0015022703388193760e1e62c054b9cbb332346c9785cb5000', max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('user_image', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('summary', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default='00150227033881985212a5b4c3b43e28057ca363a8a5afd000', max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('user_image', models.CharField(max_length=500, null=True)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default='0015022703388183aedf5558d9e41e188439af4c72dcf9a000', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('image', models.CharField(max_length=500, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
