# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default='0015020774517884216f88f23b14cc084795141da15e03f000', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='0015020774517884fece4db738f442ba47c680997d89263000', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='0015020774517873c908fe15d4a49518add3546c5ceed54000', max_length=50, primary_key=True, serialize=False),
        ),
    ]
